---
galaxy_info:
  role_name: opn_edge_decommission
  author: ContainerCraft
  description: OPNsense edge automation - opn_edge_decommission
  license: GPL-2.0-or-later
  min_ansible_version: "2.14"
dependencies: []
