---
- name: Update DNF Cache
  dnf:
    update_cache: true

- name: Update All Packages
  package:
    name: '*'
    state: latest

- name: Removing required packages
  package:
    name: "{{ packages_remove }}"
    state: absent

- name: Install required packages
  package:
    name: "{{ packages_install }}"
    state: present

- name: Install DNF Automatic Updates
  package:
    name: dnf-automatic
    state: present

- name: 'Enable Automatic Updates - Auto Apply = True'
  lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "^apply_updates = no"
    line: "apply_updates = yes"

- name: Enable DNF Automatic Update Service
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes

- name: Enable Cockpit Web Console
  systemd:
    name: cockpit
    state: started
    enabled: yes