---
- name: 'ContainerCraft Collection | kubespray | Host Prep' 
  hosts: k8s_cluster
  become: true
  collections:
  - containercraft.kubespray
  tasks:

  - name: Wait for cloud-init / user-data to finish
    command: cloud-init status --wait
    changed_when: false
    ignore_errors: yes

  - import_role:
      name: containercraft.kubespray.packages
    tags:
      - packages

  - import_role:
      name: containercraft.kubespray.experimental
    tags:
      - experimental
      - firewalld
      - resolved
      - grub

- name: 'ContainerCraft Collection | kubespray | High Availability' 
  hosts: etcd
  become: true
  collections:
  - containercraft.kubespray
  tasks:

  - import_role:
      name: containercraft.kubespray.haproxy
    tags:
      - haproxy

  - import_role:
      name: containercraft.kubespray.keepalived
    tags:
      - keepalived

