---
package_remove:
  - docker
  - cockpit
  - zram-generator
  - zram-generator-defaults
packages_install:
  - lvm2
  - python3
  - haproxy
  - iptables
  - util-linux
  - libibverbs
  - keepalived
  - dnf-automatic
  - NetworkManager-tui
