---
galaxy_info:
  role_name: opn_users
  author: ContainerCraft
  description: OPNsense edge automation - user, group, privilege management
  license: GPL-2.0-or-later
  min_ansible_version: "2.14"
dependencies: []
