#!/usr/local/bin/ansible-playbook $@
- name: 'ContainerCraft Collection | kubespray | main.yml' 
  hosts: kube_node
  collections:
  - containercraft.kubespray
  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  become: true
  vars:
    vrrp_id: 42
    vrrp_nic: br0
    vrrp_address: 192.168.16.60/24
  tasks:

  - name: Wait for cloud-init / user-data to finish
    command: cloud-init status --wait
    changed_when: false

  - import_role:
      name: packages
    tags:
      - packages

  - import_role:
      name: experimental
    tags:
      - experimental
      - firewalld
      - resolved
      - grub

  - import_role:
      name: haproxy
    tags:
      - haproxy

  - import_role:
      name: keepalived
    tags:
      - keepalived
