name: Build & Publish Konductor Kubespray Container
on:
  repository_dispatch:
    types:
      - container
  schedule:
    - cron: '0 1 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches:
      - master

jobs:
  build-and-publish-image:
    runs-on: ubuntu-20.04
    steps:

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Git Checkout
      uses: actions/checkout@v2.4.0
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Login Docker.io
      uses: docker/login-action@v1.12.0
      with:
        logout: true
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Login Quay.io
      uses: docker/login-action@v1.12.0
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Rake Variables
      id: rake_vars
      run: |
        set -x ; \
        echo ::set-output name=VARRUNDATE::$(date +%y%m%d%I%M%S); \
        echo;

    - name: Build Image
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./containers/kubespray
        file: ./containers/kubespray/Dockerfile
        push: true
        tags: |
          quay.io/containercraft/konductor:kubespray
          quay.io/containercraft/konductor:kubespray-${{ steps.rake_vars.outputs.VARRUNDATE }}-${{ github.sha }}

          docker.io/containercraft/konductor:kubespray
          docker.io/containercraft/konductor:kubespray-${{ steps.rake_vars.outputs.VARRUNDATE }}-${{ github.sha }}

        build-args: |
          varRunDate=${{ steps.rake_vars.outputs.VARRUNDATE }}
          varVerOpenshift=kubespray