name: konductor-kubespray
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - master
  repository_dispatch:
    types: [konductor-kubespray]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1

    - name: Git Checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Login Docker.io
      uses: docker/login-action@v1.10.0
      with:
        logout: true
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Rake Variables
      run: |
        set -x ; \
        echo "varrundate=$(date +%y%m%d%I%M%S)" >> ${GITHUB_ENV};\
        echo;  

    - name: Build Image 
      uses: docker/build-push-action@v2.6.1
      with:
        context: ./containers/kubespray
        file: ./containers/kubespray/Dockerfile
        push: true
        tags: |
          quay.io/containercraft/konductor
          quay.io/containercraft/konductor:kubespray
          quay.io/containercraft/konductor:kubespray-${{ env.varrundate }}-${{ github.sha }}

          docker.io/containercraft/konductor
          docker.io/containercraft/konductor:kubespray
          docker.io/containercraft/konductor:kubespray-${{ env.varrundate }}-${{ github.sha }}

        build-args: |
          varRunDate=${{ env.varrundate }}
          varVerOpenshift=kubespray
