name: Build and Publish
on:
  create:
    tags:
      - '*'

jobs:
  build-and-publish-collection:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2.4.0

    - name: Export Variables
      id: github_ref
      run: |
        set -ex; \
        echo "github_ref: $GITHUB_REF" ;\
        echo ::set-output name=GITHUB_REF_TAG::$(echo $GITHUB_REF | awk -F/ '{print $NF}' | awk -F- '{print $NF}'); \
        echo;

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install ansible
      run: pip install -U ansible

    - name: Template Ansible File galaxy.yml
      run: |
        ansible localhost --connection local \
          -i localhost -m template \
          -a "src=templates/kubespray-galaxy.yml.j2 dest=kubespray/galaxy.yml" \
          -e github_ref=0.${{ steps.github_ref.outputs.GITHUB_REF_TAG }}

    - name: Build & Publish Collection | Kubespray
      run: |
        set -x ; \
        mkdir -p galaxy ;\
        ansible-galaxy collection build --output-path galaxy kubespray ;\
        ansible-galaxy collection publish --api-key=${{ secrets.ANSIBLE_GALAXY_API_KEY }} \
        galaxy/containercraft-kubespray-${{ github_ref }}.tar.gz ; \
        echo;
        variables: |
          github_ref=0.${{ steps.github_ref.outputs.GITHUB_REF_TAG }}

  build-and-publish-image:
    runs-on: ubuntu-20.04
    needs: build-and-publish-collection
    steps:

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Git Checkout
      uses: actions/checkout@v2.4.0
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Login Docker.io
      uses: docker/login-action@v1.10.0
      with:
        logout: true
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Login Quay.io
      uses: docker/login-action@v1.10.0
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}

    - name: Rake Variables
      id: rake_vars
      run: |
        set -x ; \
        echo ::set-output name=VARRUNDATE::$(date +%y%m%d%I%M%S); \
        echo;

    - name: Build Image
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./containers/kubespray
        file: ./containers/kubespray/Dockerfile
        push: true
        tags: |
          quay.io/containercraft/konductor:kubespray
          quay.io/containercraft/konductor:kubespray-${{ steps.rake_vars.outputs.VARRUNDATE }}-${{ github.sha }}

          docker.io/containercraft/konductor:kubespray
          docker.io/containercraft/konductor:kubespray-${{ steps.rake_vars.outputs.VARRUNDATE }}-${{ github.sha }}

        build-args: |
          varRunDate=${{ steps.rake_vars.outputs.VARRUNDATE }}
          varVerOpenshift=kubespray
