name: Workflow Dispatcher
on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1

    - name: Build Ansible Kubespray Collection
      if: success()
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        event-type: ansible-galaxy-kubespray
        repository: ${{ github.repository }}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
        token: ${{ secrets.GH_ACTIONS_TOKEN }}
